MySQL_Info:
  MySQL_Username: "root"
  MySQL_Password: "deVeloPersecuRity"
  MySQL_Network:  "tcp"
  MySQL_IP: "ssppw-sql"
  MySQL_Port: 3306
  MySQL_Datbase:  "ssppw-sql"
iscontainer: false
Stock_Info_IP: ssppw-stock-info
Stock_Info_port: ":8902"