services:
  ssppw-user-account:
    image: ssppw-user-account
    networks:
      - ssppw-default-network
    ports:
      - 8900:8900

    container_name: ssppw-user-account

  ssppw-stock-center:
    image: ssppw-stock-center
    networks:
      - ssppw-default-network
    ports:
      - 8901:8901
    container_name: ssppw-stock-center

  ssppw-stock-info:
    image: ssppw-stock-info
    networks:
      - ssppw-default-network

    container_name: ssppw-stock-info

  ssppw-api-gateway:
    image: ssppw-api-gateway
    ports:
      - 127.0.0.1:8899:8899
    networks:
      - ssppw-default-network
    links:
      - ssppw-user-account:ssppw-user-account
      - ssppw-stock-center:ssppw-stock-center
    
    container_name: ssppw-api-gateway

  ssppw-frontend:
    image: ssppw-frontend
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - ssppw-default-network
    
    
    container_name: ssppw-frontend

    
networks:
  ssppw-default-network:
    name: ssppw-default-network
    external: true